### ISSUE TITLE
Shellfire VPN for Windows Clicking "Disconnect" issues an indicator that shows "Connecting"

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#30]
it should say "Disconnecting" instead

**Comment by flogat** [comment]
test needed after rebuild

**Comment by mbehrsf** [comment]
With the current build, when I hit "Disconnect" the connection gets disconnected after a few seconds of freezing, there is no more "Connecting" indicator but also no "Disconnecint" indicator so you don't really know what's happening.

**Comment by Tcheutchoua-Steve** [comment]
Investigating this now.

**Comment by Tcheutchoua-Steve** [comment]
Based on this commit https://github.com/shell-fire/shellfire-vpn/commit/133d9f96a8b3d6fb57fe737ba5a7a3f7ffdf3fa6 which affects the service, it says "because service is effected, new build and re-installation required.", how can I have the new build/service @flogat ?

**Comment by flogat** [comment]
fyi - steve received an updated build via another channel.

@mbehrsf please retest

**Comment by mbehrsf** [comment]
issue remains unchanged with the lastest build

**Comment by Tcheutchoua-Steve** [comment]
The swing version had the popup message "`Connection is being processed...`" when ever `connection/disconnection` was going on. This is was sort of suitable as a message, for both connection and disconnection. 
I could revert to using that message for both instances. However, if we need to maintain `Connecting/Disconnecting` messages, it is doable but will require some tweaking. I just thought of letting you know so that you make the call. 
@flogat

**Comment by flogat** [comment]
For the sake of simplicity and an earlier "done" version, we do it simple now put "Connection is being processed" again.
